# Generated by Django 4.1.4 on 2023-02-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_results_name_alter_results_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='age',
        ),
    ]
